version: "3"
services:
  db:
    image: mongo:3.6.1
    container_name: "mongodb"
    hostname: mongodb
    ports:
      - "27017:27017"
  rabbitmq:
    image: rabbitmq:3.7.4
    container_name: "rabbitmq"
    hostname: rabbitmq
    ports:
      - "5671:5671"
      - "5672:5672"
      - "15672:15672"
  sat:
    build: .
    container_name: "sat"
    depends_on:
      - db
      - rabbitmq
    ports:
      - "5000:5000"
